name: Code test

on:
  push: 
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install compiler
        run: sudo apt-get install g++
        
      - name: Compilation
        run: g++ main.cpp GameTest.cpp Game.cpp Board.cpp -o ticTacToe
      
      - name: Run tic tac tow test
        run: ./ticTacToe
        